CREATE DATABASE "Alpha"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Bravo"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Charlie"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Delta"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Echo"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Foxtrot"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Golf"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Hotel"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "India"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Juliet"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Kilo"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Lima"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Mike"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "November"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Oscar"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Papa"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Quebec"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Romeo"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Sierra"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Tango"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Uniform"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Victor"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Whiskey"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "X-ray"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Yankee"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
CREATE DATABASE "Zulu"
  WITH ENCODING='UTF8'
       CONNECTION LIMIT=-1;
